// Live unit gallery. Runs the real sprite code on canvas with the game's animation states:
//   idle   - the unit is ready: idle animation running          (what you see on your turn)
//   moving - the unit is sliding across the map: animation at double speed
//   done   - the unit has acted: static pose, faded
// The page shell (index.html) is generated by `node tools/sprite-lab/lab.mjs gallery`; this file is hand-written.
import { SPRITES, SHADOWS } from '../src/render/unit-art.js';
import { drawFrameAlpha } from '../src/render/unit-frame.js';

const MOD = { SPRITES, SHADOWS };
export const STATES = { idle: { run: 1, speed: 1, alpha: 1 }, moving: { run: 1, speed: 2, alpha: 1 }, done: { run: 0, speed: 1, alpha: .55 } };

/** Paint one tile (backdrop + unit) into a 2D context that is already scaled to CSS pixels. Pure drawing: no DOM. */
export function paintTile(g, { unit, faction, size, t, state, phase, bg }) {
  const st = STATES[state] || STATES.idle;
  g.clearRect(0, 0, size, size);
  g.fillStyle = bg; g.fillRect(0, 0, size, size);
  g.save(); g.translate(size / 2, size / 2);
  drawFrameAlpha(g, MOD, unit.sprite, { s: size, c: faction.color, dk: faction.dark, alt: unit.altitude || 0, w: t * st.speed, ph: phase, run: st.run }, st.alpha);
  g.restore();
}

// ---- page ----------------------------------------------------------------------------------------------------
async function boot() {
  const DATA = await (await fetch(new URL('data.json', import.meta.url))).json();
  const $ = (sel) => document.querySelector(sel);
  const state = { mode: 'idle', size: 96, bg: 'plain', paused: matchMedia('(prefers-reduced-motion: reduce)').matches };
  let clock = 0, last = performance.now();

  const grid = $('#grid');
  const tiles = [];   // { canvas, g, unit, faction, phase, visible }
  DATA.units.forEach((unit, ui) => {
    const card = document.createElement('div'); card.className = 'card';
    const name = document.createElement('div'); name.className = 'name'; name.textContent = unit.name;
    const note = document.createElement('div'); note.className = 'note'; note.textContent = unit.note;
    const row = document.createElement('div'); row.className = 'row';
    DATA.factions.forEach((faction, fi) => {
      const canvas = document.createElement('canvas'); canvas.setAttribute('role', 'img'); canvas.setAttribute('aria-label', `${unit.name}, ${faction.name}`);
      row.append(canvas);
      tiles.push({ canvas, g: canvas.getContext('2d'), unit, faction, phase: ui * 1.3 + fi * .7, visible: true });
    });
    card.append(name, note, row); grid.append(card);
  });

  const io = 'IntersectionObserver' in window ? new IntersectionObserver((entries) => entries.forEach((e) => { tiles.find((t) => t.canvas === e.target).visible = e.isIntersecting; })) : null;
  if (io) tiles.forEach((t) => io.observe(t.canvas));

  function resize() {
    const dpr = window.devicePixelRatio || 1, S = state.size;
    document.documentElement.style.setProperty('--s', S + 'px');
    for (const t of tiles) { t.canvas.width = Math.round(S * dpr); t.canvas.height = Math.round(S * dpr); t.canvas.style.width = t.canvas.style.height = S + 'px'; t.g.setTransform(dpr, 0, 0, dpr, 0, 0); }
    draw();
  }
  function draw() {
    const bg = DATA.terrain[state.bg];
    for (const t of tiles) if (t.visible) paintTile(t.g, { unit: t.unit, faction: t.faction, size: state.size, t: clock, state: state.mode, phase: t.phase, bg });
  }
  function frame(now) {
    if (!state.paused) clock += (now - last) / 1000;
    last = now; draw(); requestAnimationFrame(frame);
  }

  // controls
  const group = (sel, key, after) => document.querySelectorAll(`${sel} button`).forEach((b) => b.addEventListener('click', () => {
    state[key] = b.dataset.v; document.querySelectorAll(`${sel} button`).forEach((x) => x.setAttribute('aria-pressed', String(x === b))); if (after) after(); draw();
  }));
  group('#mode', 'mode'); group('#bg', 'bg');
  $('#size').addEventListener('input', (e) => { state.size = Number(e.target.value); $('#sizeOut').textContent = state.size + ' px'; resize(); });
  const pauseBtn = $('#pause');
  const syncPause = () => { pauseBtn.textContent = state.paused ? 'Play' : 'Pause'; pauseBtn.setAttribute('aria-pressed', String(state.paused)); };
  pauseBtn.addEventListener('click', () => { state.paused = !state.paused; syncPause(); });
  syncPause(); resize(); requestAnimationFrame(frame);
}

if (typeof document !== 'undefined') await boot();
